### ISSUE TITLE
Advice needed, able to parse but not build when having variable length

### ISSUE THREAD

**Issue by potens1** [construct/construct#324]
Hi,

I'm trying to implement the xbee protocol, I'm able to parse raw bytes, but I'm unable to build it.

<noob_life>
I'm still trying to find the "good" way to wrap my head around construct but I encounter some difficulties.

The biggest difficulties I have are when trying to read back data and when trying to use variable length structures. I've tried the next code with Union, Pointers and few other things, but, at a point or another I encounter errors (because of lack of understanding, I guess)
</noob_life>

So, the following works well to decode, but encoding does not. In this code, the len of dataf can not be computed (and should not) the "length" field is evaluated to 1, then 1-12 -> -11. I'm convinced I missed something, but I don't get it. Any advice on a) how to get that working, b) what is the best way to achieve those kinds of things. 
 
```py
from construct import *

xbframe = Struct(
    Const(b'\x7E'),
    "length" / Rebuild(Int16ub, len_(this.framedata)),
    "framedata" / RawCopy(
        Struct(
            "frame_type" / Enum(
                Byte,
                RX=0x90
            ),
            "df" / Switch(
                this.frame_type,
                {
                    "RX": Struct(
                        "source" / Byte[8],
                        "short_source" / Byte[2],
                        "options" / FlagsEnum(
                            Byte,
                            ack=0x01,
                            broadcast=0x02,
                            aps=0x20,
                            from_end_device=0x40),
                        "dataf" / String(this._._.length - 12, encoding="utf8")
                    )
                }
            )
        )
    ),
    "checksum" / Checksum(Bytes(1),
                          lambda data: bytes((0xFF - sum(data) & 0xFF,)),
                          this.framedata.data)
)

test = b"\x7e\x00\x19\x90\x00\x13\xa2\x00\x40\x86\x5e\x74\xbb\x2d\x41\x32\x30\x2e\x38\x30\x3b\x35\x37\x2e\x35\x38\x0d\x0a\xa8"
test2 = {
    "framedata": {
        "value": {
            "frame_type": "RX",
            "df": {
                "source": [1, 2, 3, 4, 5, 6, 7, 8],
                "short_source": [1, 2],
                "options": {"ack": True},
                "dataf": u"baz"}
        }
    }
}


print(xbframe.parse(test))
print(xbframe.build(test2))
```
Output is:
```py
Container: 
    length = 25
    framedata = Container: 
        data = b'\x90\x00\x13\xa2\x00@\x86^t\xbb-A20.80;57.58\r\n'
        value = Container: 
            frame_type = RX
            df = Container: 
                source = ListContainer: 
                    0
                    19
                    162
                    0
                    64
                    134
                    94
                    116
                short_source = ListContainer: 
                    187
                    45
                options = FlagsContainer: 
                    ack = True
                    from_end_device = True
                dataf = 20.80;57.58
                
        offset1 = 3
        offset2 = 28
        length = 25
    checksum = b'\xa8'
Traceback (most recent call last):
  File "sansbee.py", line 53, in <module>
    print(xbframe.build(test2))
  File "/tmp/bee/lib/python3.6/site-packages/construct/core.py", line 203, in build
    self.build_stream(obj, stream, context, **kw)
  File "/tmp/bee/lib/python3.6/site-packages/construct/core.py", line 215, in build_stream
    self._build(obj, stream, context, "building")
  File "/tmp/bee/lib/python3.6/site-packages/construct/core.py", line 874, in _build
    buildret = sc._build(subobj, stream, context, path)
  File "/tmp/bee/lib/python3.6/site-packages/construct/core.py", line 2723, in _build
    return self.subcon._build(obj, stream, context, path)
  File "/tmp/bee/lib/python3.6/site-packages/construct/core.py", line 2149, in _build
    data = self.subcon.build(value, context)
  File "/tmp/bee/lib/python3.6/site-packages/construct/core.py", line 203, in build
    self.build_stream(obj, stream, context, **kw)
  File "/tmp/bee/lib/python3.6/site-packages/construct/core.py", line 215, in build_stream
    self._build(obj, stream, context, "building")
  File "/tmp/bee/lib/python3.6/site-packages/construct/core.py", line 874, in _build
    buildret = sc._build(subobj, stream, context, path)
  File "/tmp/bee/lib/python3.6/site-packages/construct/core.py", line 2723, in _build
    return self.subcon._build(obj, stream, context, path)
  File "/tmp/bee/lib/python3.6/site-packages/construct/core.py", line 1573, in _build
    case._build(obj, stream, context, path)
  File "/tmp/bee/lib/python3.6/site-packages/construct/core.py", line 874, in _build
    buildret = sc._build(subobj, stream, context, path)
  File "/tmp/bee/lib/python3.6/site-packages/construct/core.py", line 2723, in _build
    return self.subcon._build(obj, stream, context, path)
  File "/tmp/bee/lib/python3.6/site-packages/construct/core.py", line 315, in _build
    return self.subcon._build(self._encode(obj, context), stream, context, path)
  File "/tmp/bee/lib/python3.6/site-packages/construct/core.py", line 315, in _build
    return self.subcon._build(self._encode(obj, context), stream, context, path)
  File "/tmp/bee/lib/python3.6/site-packages/construct/core.py", line 401, in _build
    _write_stream(stream, length, data)
  File "/tmp/bee/lib/python3.6/site-packages/construct/core.py", line 80, in _write_stream
    raise ValueError("length must be >= 0", length)
ValueError: ('length must be >= 0', -11)
```

**Comment by arekbulski** [comment]
You measure len of a dict, not a bytes item in it. 
```py
 "length" / Rebuild(Int16ub, len_(this.framedata.data)), 
```

**Comment by arekbulski** [comment]
I would consider using `Prefixed and GreedyString`. Perhaps `Bytes` instead of byte arrays?

**Comment by potens1** [comment]
Hi,
Thank you for your advice. I've tried with the Prefixed + GreedyString, but, I'm still unable to build since the "data" for the RawCopy seems not to be built yet at the time the Checksum must be computed.

That's the point when I often come. I'm able to either parse or build, but not the two.

About the len of the dict, I saw it, but, I was wondering, on a raw copy, don't you think it could be useful to have the sizeof overridden to be computed on the len of data (if available) or the len of values ?

**Comment by arekbulski** [comment]
Sizeof is not used there, you call len on a dict object.

**Comment by arekbulski** [comment]
Could it be you experience this bug? https://github.com/construct/construct/issues/325

**Comment by potens1** [comment]
I don't think so since the hash can not be built the problem I'm encountering is when the lambda function is ran on building, the content is only a dict 
```{'value': {'frame_type': 'RX', 'df': {'source': [1, 2, 3, 4, 5, 6, 7, 8], 'short_source': [1, 2], 'options': {'ack': True}, 'dataf': 'baz'}}}```

and I really don't get the difference between my code and the example one:

```
import hashlib
d = Struct(
    "fields" / RawCopy(Struct(
        "a" / Byte,
        "b" / Byte,
    )),
    "checksum" / Checksum(Bytes(64), lambda data: hashlib.sha512(data).digest(), this.fields.data),
)
data = d.build(dict(fields=dict(value=dict(a=1,b=2))))
```
In the example, when entering the lambda, data exists and contains the bytes built from the the RawCopy, mine is having only the dict of values. Maybe my brain is off right now, but, it seems to me one to one between my code and the example:

fields is the RawCopy, in my code it is framedata
the bytesfunc is this.fields.data, in my code it is this.framedata.data

**Comment by arekbulski** [comment]
Use mainstream version, fixes were not published yet. Then can you PR a proper test case?

**Comment by potens1** [comment]
So there is no problem in my code, it should work ? (example is working, at least). Then, I'll try to do the smallest example not working.

**Comment by arekbulski** [comment]
Your last code works fine.

**Comment by arekbulski** [comment]
Your last code works fine. Also works fine if you use Bytes there.

**Comment by potens1** [comment]
Done here: #328 

If you want I move the test somewhere else, feel free to comment. I've put it near checksum tests but in fact I think it's more a RawCopy bug (if this is a bug)

**Comment by arekbulski** [comment]
Its not, you made two mistakes. (1) Prefixed itself wasnt named, it doesnt matter how its two subcons are named because those are ignored. (2) Byte[2] is an array, its not Bytes(2) which is a bytes. But this still doesnt solve it... yet

**Comment by arekbulski** [comment]
Strike that, only one mistake: Byte[2] is an array, its not Bytes(2) which is a bytes. Still working on it.

**Comment by arekbulski** [comment]
Strike that, only one mistake: Byte[2] is an array, its not Bytes(2) which is a bytes. 

You also hit several bugs in RawCopy Checksum and Prefixed at once. Congratulations. I officially give you an achivement "gold miner". Please wait few days, I need some time to fix all this.

**Comment by arekbulski** [comment]
Strike that, only two mistakes: Byte[2] is an array, its not Bytes(2) which is a bytes. Second is that `sum(data)` doesnt work when data is bytes, fails on PY2.

You also hit several bugs in RawCopy Checksum and Prefixed at once. Congratulations. I officially give you an achivement "gold miner". Please wait few days, I need some time to fix all this.

**Comment by arekbulski** [comment]
Modified your code to be correct, but it wont work until I fixed the 3 classes too.
```py3
d = Struct(
    "vals" / Prefixed(Byte, RawCopy(
        Struct(
            "a" / Byte[2]
        ),
    )),
    Probe(),
    "checksum" / Checksum(
        Byte,
        lambda data: sum(iterateints(data)) & 0xFF,
        this.vals.data
    ),
)
assert d.build(dict(vals=dict(value=dict(a=[0,1])))) == b"\x02\x00\x01\x01" 
assert d.build(dict(vals=dict(data=b"\x00\x01"))) == b"\x02\x00\x01\x01" 
```

**Comment by arekbulski** [comment]
Issues were fixed. Your code was added to the test suite and passes green. :smile:

**Comment by potens1** [comment]
Thanks a lot !
